---
title: "HABcor"
author: "Natalie Dornan"
date: "March 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(stringr)
library(leaflet)
library(ggrepel)
library(ggspatial)
library(RColorBrewer)
library(rgdal)
library(shiny)


# Interactive Map
library(sf)
library(tmap)
library(sp)
library(spatstat)
library(gstat)
library(raster)
library(maptools)
library(rgeos)

select <- dplyr::select
```

```{r, troubleshoot server}

hab_new <- read_csv("clean_hab.csv") %>%
  rename("Akashiwo sp." = akashiwo,
         "Alexandrium spp." = alexandrium ,
         "Ammonia" = ammonia,
         "Chlorophyll" = chlorophyll,
         "Domoic Acid" = domoic_acid,
         "Phosphate" = phosphate,
         "Pseudo Nitzschia spp." = pseudo_nitzschia_spp,
         "N+N" = n_n,
         "Silicate" = silicate,
         "Water Temp" = water_temp) # Rename variables

write.csv(hab_new, "hab_new.csv")

```

```{r, ui}

## to make Input dropdown 

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("HAB Correlation Plots"),
   
   # Sidebar 
   sidebarLayout(
      sidebarPanel(
        
        ##create select box with locations
        
        selectInput(inputId = "station", label = h3("Station Name"), 
                    choices = list("Cal Poly Pier", 
                                   "Goleta Pier", 
                                   "Stearn's Wharf", 
                                   "Santa Monica Pier", 
                                   "Newport Pier", 
                                   "Scripps Pier"), 
                    selected = 1),
       
    br(),
    uiOutput("choose_result"),
    
    uiOutput("choose_regressors"),
    br(),
      
        ##create group checkbox for x variables
      
#      checkboxGroupInput(inputId = "result", label = h3("Dependent Variables"), 
 #                        choices = list("Akashiwo sp.", 
  #                                      "Alexandrium spp.", 
   #                                     "Ammonia", 
    #                                    "Chlorophyll", 
     #                                   "Domoic Acid", 
      #                                  "N+N", 
       #                                 "Phosphate", 
        #                                "Silicate", 
         #                               "Water Temp"),
          #               selected = 1),
      

      ##create group checkbox for y variables     
      
      checkboxGroupInput(inputId = "regressors", label = h3("Independent Variables"), 
                         choices = list("Akashiwo sp." = 1, 
                                        "Alexandrium spp." = 2, 
                                        "Ammonia" = 3, 
                                        "Chlorophyll" = 4, 
                                        "Domoic Acid" = 5, 
                                        "N+N" = 6, 
                                        "Phosphate" = 7,
                                        "Silicate" = 8, 
                                        "Water Temp" = 9),
                         selected = 1)
         
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
        tabsetPanel(
        tabPanel("Application",     
                 plotOutput("scatter"),
                 tableOutput("lmStats"),
                 tableOutput("lmResults"),
                 tableOutput("values")))
      )
   )
)


```



```{r}

print(getwd())
# "print" comments were scaffolding for debugging the application
data.maker <- function(data, y, x) {
#   print("Line 6")
#   print(y)
  if(is.null(y)) res1=data[, 1] else res1=data[, y]
#   print(res1)
  if(is.null(x)) regr1=data[, 6] else regr1=data[, x]
#   print(x)
#   print("Line 12")

  data.frame(x=regr1,x2=x2,x3=x3,sqrtx=sqrtx,logx=logx,expx=expx,y=res1)
}

server <- function(input, output) {
  mydata <- reactive({
    
#     print("Line 24. First line after mydata <- reactive ")
    # Define the data set and its columns
    # If missing input, return to avoid error later in function
    if(is.null(input$station))
      return()
#     print("Line 29")
    dat <<- get(input$station)
#    print(dat)
#     print("Line 32")
    columns <<- colnames(dat)
#     print(columns)
    # Make sure columns are correct for data set (when data set changes, the
    # columns will initially be for the previous data set)
    if (is.null(columns) || !(columns %in% names(dat)))
      return()

#     print("Line 40. Before selecting input$result ")
    res <<- input$result
#     print(res)
#     
#     print("Line 44")
    # Make sure result is correct for data set (when data set changes, the
    # result will initially be for the previous data set)
    if (is.null(input$regressors) || !(input$regressors %in% names(dat)))
      return()
    
    regr <<- input$regressors
#     print(regr)
#     print("Line 52. Just before data.maker ")
    data.maker(data=dat, y=res, x=regr)
  })
  
  # Pick the resulting variable
  output$choose_result <- renderUI({
#     print("Line 58. Within choose_result")
    dat <<- get(input$station)
#     print("Line 60. Within choose_result")
    # Make sure columns are correct for data set (when data set changes, the
    # columns will initially be for the previous data set)
    columns <<- colnames(dat)
#     print(columns)
    if (is.null(columns) || !(columns %in% names(dat)))
      return()
#     print("Line 67. Within choose_result")
    selectInput("result","Pick resulting variable",
                as.list(columns),
                selected=columns[1])
  })
  
  # Select the required regressors (Check boxes)
  output$choose_regressors <- renderUI({
#     print("Line 75")
    dat <<- get(input$station)
#     print("Line 77. Within choose_regressors ")
    columns <<- colnames(dat)
    # Make sure columns are correct for data set (when data set changes, the
    # columns will initially be for the previous data set)
    if (is.null(columns) || !(columns %in% names(dat)))
      return()
#     print("Line 83")
    # Create the checkboxes and select the default regressor
    radioButtons("regressors", "Choose regressors", 
                       choices  = columns,
                       selected = columns[6])
  })
  
  output$values <- renderTable({
#       print("Line 91. Within output$values")
      mydata()
  })

  lmResults <- reactive({
#     print("Line 96. Within lmResults")
    
    regress.exp <<- input$regression
    if (!input$constant) regress.exp <- paste(input$regression, "- 1")

#     print("Line 101. Before lm(...")
#     print(regress.exp)
#    print(mydata())
    lm(regress.exp, data=mydata())
  })

  output$lmStats <- renderTable({
    
    # Make sure result is correct for data set (when data set changes, the
    # result will initially be for the previous data set)
    if (is.null(input$result) || !(input$result %in% names(dat)))
      return()
#     print("Line 113. Before results <- summary(lmResults())")
    
    results <<- summary(lmResults())
    data.frame(R2=results$r.squared,
               adj.R2=results$adj.r.squared,
               DOF.model=results$df[1],
               DOF.available=results$df[2],
               DOF.total=sum(results$df[1:2]),
               f.value=results$fstatistic[1],
               f.denom=results$fstatistic[2],
               f.numer=results$fstatistic[3],
               p=1-pf(results$fstatistic[1],
                      results$fstatistic[2],
                      results$fstatistic[3]))
  })


  # Show coefficients
  output$lmResults <- renderTable({
    
    # Make sure result is correct for data set (when data set changes, the
    # result will initially be for the previous data set)
    if (is.null(input$result) || !(input$result %in% names(dat)))
      return()
#     print("Line 137. Before summary(lmResults())")
    
    summary(lmResults())
  })

  # Show plot of points, regression line, residuals
  output$scatter <- renderPlot({
#     print("Line 144. Beginning scatterPlot")
# print(mydata())     
    data1 <<- mydata()
if(length(data1) > 0){
#     print("Line 148")
#     print(data1$x)
    x <<- data1$x
#     print("Line 151")
#     print(data1$y)
    y <<- data1$y
#     print("Line 154")
    xcon <- seq(min(x)-.1, max(x)+.1, .025)
    x2 <<- xcon^2
    x3 <<- xcon^3
    sqrtx <<- sapply(xcon, function(x) {if(x > 0) sqrt(x) else 0})
    logx <<- sapply(xcon, function(x) {if(x > 0) log(x) else -100})
    expx <<- exp(xcon)

    predictor <<- data.frame(x=xcon,x2=x2,x3=x3,sqrtx=sqrtx,logx=logx,expx=expx)
    yhat <<- predict(lmResults())
    yline <<- predict(lmResults(), predictor)
    plot(c(min(x),max(x))
         ,c(min(y,yline),max(y,yline)),
         type="n",
         xlab=as.character(input$regressors),
         ylab=as.character(input$result),
         main=paste0("Regression Model: ", input$regression))

    if (input$predict) lines(xcon, yline, lwd=15, col=grey(.9))
    if (input$resid) for (j in 1:length(x))
      lines(rep(x[j],2), c(yhat[j],y[j]), col="red")
    if (input$showdata) points(x,y)
    if (input$predict) lines(xcon, yline, lwd=2, col="blue")
}

  })
}

```

