---
title: "ShinyMushu"
author: "Laura Ingulsrud, Sidney Gerst, Natalie Dornan"
date: "2/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

library(tidyverse)
library(janitor)
library(lubridate)
library(stringr)
library(leaflet)
library(ggrepel)
library(ggspatial)
library(RColorBrewer)
library(rgdal)

# Time series
library(tseries)
library(forecast)
library(lubridate)

# Interactive Map
library(sf)
library(tmap)
library(sp)
library(spatstat)
library(raster)
library(maptools)
library(rgeos)


select <- dplyr::select

```

```{r data}

HAB <- read_csv("HAB.csv") # Read in data: "Harmful Algal Blooms 2008-2019"

# Clean up the data
clean_hab <- HAB %>% 
  clean_names(., case = c("snake")) %>% # Convert to snake case
  dplyr::select(year, month, day, latitude, longitude, location, akashiwo_sanguinea_cells_l, alexandrium_spp_cells_l, ammonia_u_m, chlorophyll_mg_m3, domoic_acid_ng_m_l, nitrate_u_m, nitrite_u_m, phosphate_u_m, pseudo_nitzschia_delicatissima_group_cells_l, pseudo_nitzschia_seriata_group_cells_l, silicate_u_m, water_temperature_c) %>% # Selected species that are correlated with HABs
  na.omit() %>% # Remove "NaNs" 
  rename(akashiwo = akashiwo_sanguinea_cells_l,
         alexandrium = alexandrium_spp_cells_l,
         ammonia = ammonia_u_m,
         chlorophyll = chlorophyll_mg_m3,
         domoic_acid = domoic_acid_ng_m_l,
         nitrate = nitrate_u_m,
         nitrite = nitrite_u_m,
         phosphate = phosphate_u_m,
         pseudo_nitzschia_delicatissima = pseudo_nitzschia_delicatissima_group_cells_l,
         pseudo_nitzschia_seriata = pseudo_nitzschia_seriata_group_cells_l,
         silicate = silicate_u_m,
         water_temp = water_temperature_c) %>% # Rename variables
  mutate(year_month = str_c(year, month, sep = "-")) %>% # Create one column of year and month of sample together
  mutate("n_n" = nitrate + nitrite) %>%
  mutate(pseudo_nitzschia_spp = pseudo_nitzschia_delicatissima + pseudo_nitzschia_seriata)## sum N+N concentrations

##create csv file of clean_hab df

write.csv(clean_hab, "clean_hab.csv")

```

```{r LAURA - Tab 2: HAB abundance chart}

chlorophyll_col <- ggplot(clean_hab, aes(x = month, y = chlorophyll)) +
  geom_col(fill = "seagreen3", color = "seagreen") +
  labs(x = "Month", y = "Chlorophyll Concentration (mg/L)") +
  theme_bw() 

chlorophyll_col

domoic_col <- ggplot(clean_hab, aes(x = month, y = domoic_acid)) +
  geom_col(fill = "cornflowerblue", color = "royalblue") +
  labs(x = "Month", y = "Domoic Acid Concentration (mg/L)") +
  theme_bw() 

domoic_col

##laura was this across all years? really interesting stuff. Chl a is highest in May but domoic acid is highest in April! 

```

```{r TIME SERIES GRAPH}

HAB_dates <- clean_hab %>%
 unite_("date", c("year", "month", "day")) %>% 
  dplyr::select(date,
                chlorophyll) %>% 
  isoyear(as.Date(date))



# Create 'ts' time series data using information in the res_total column from 'energy'

HAB_ts <- ts(HAB_dates$chlorophyll, frequency = 12, start = c(2008,1))

HAB_ts

plot(HAB_ts)

```


```{r NATALIE - Tab 3: Correlation plot}

## Set the purpose: To create a friendly widget that will allow users to explore abiotic and biotic relationships relating to HAB occurence. ex)

hab_cor <- clean_hab %>%
  select(year_month, location, akashiwo, alexandrium, ammonia, chlorophyll, domoic_acid, n_n, phosphate, silicate,     water_temp)

##model_name <- lm(y_variable ~ x_variable, data = df_name)

temp_lm <- lm(chlorophyll ~ water_temp, data = hab_cor)

summary(temp_lm)

ggplot(hab_cor, aes(x = water_temp, y = chlorophyll)) +
  geom_point() +  
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(temp_lm)$adj.r.squared, 5),
                     "Intercept =",signif(temp_lm$coef[[1]],5 ),
                     " Slope =",signif(temp_lm$coef[[2]], 5),
                     " P =",signif(summary(temp_lm)$coef[2,4], 5)))

#####

n_lm <- lm(chlorophyll ~ n_n, data = hab_cor)

summary(n_lm)

ggplot(hab_cor, aes(x = n_n, y = chlorophyll)) +
  geom_point() +  
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(n_lm)$adj.r.squared, 5),
                     "Intercept =",signif(n_lm$coef[[1]],5 ),
                     " Slope =",signif(n_lm$coef[[2]], 5),
                     " P =",signif(summary(n_lm)$coef[2,4], 5)))

######

domoic_lm <- lm(chlorophyll ~ domoic_acid, data = hab_cor)

summary(domoic_lm)

ggplot(hab_cor, aes(x = domoic_acid, y = chlorophyll)) +
  geom_point() +  
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(domoic_lm)$adj.r.squared, 5),
                     "Intercept =",signif(domoic_lm$coef[[1]],5 ),
                     " Slope =",signif(domoic_lm$coef[[2]], 5),
                     " P =",signif(summary(domoic_lm)$coef[2,4], 5)))
######

d_n_lm <- lm(domoic_acid ~ n_n, data = hab_cor)

summary(d_n_lm)

ggplot(hab_cor, aes(x = n_n, y = domoic_acid)) +
  geom_point() +  
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(d_n_lm)$adj.r.squared, 5),
                     "Intercept =",signif(d_n_lm$coef[[1]],5 ),
                     " Slope =",signif(d_n_lm$coef[[2]], 5),
                     " P =",signif(summary(d_n_lm)$coef[2,4], 5)))

```



```{r SIDNEY - Tab 4: Interactive Map}

#create a map of california 
ca_counties <- read_sf(".", layer = "california_county_shape_file")

# Load raster package and an example SpatialPolygonsDataFrame
data("ca_counties", package="maptools")


#This worked, as well, sort of. Able to get a map of the six locations! 
coast_counties <- ca_counties %>%
  filter(NAME %in% c("San Luis Obispo", "Santa Barbara", "Ventura", "Los Angeles", "Orange", "San Diego"))

plot(coast_counties)

st_crs(coast_counties) = 4326


#example from lab 6, sort of works.. still trying to figure out how to post each data point
sites_hab <- st_as_sf(clean_hab, coords = c("longitude", "latitude"), crs = 4326) 

str(sites_hab)

#try sf map
ggplot()+
  geom_sf(data = coast_counties, fill = "gray80") +
  geom_sf(data = sites_hab, aes(color = chlorophyll), size = 4) +
  theme_minimal()+
  coord_sf(datum = NA)



str(clean_hab)



#map of the locations of the different sites
# ggplot(coast_counties) +
#   geom_sf(data = coast_counties, 
#           fill = "NA",
#           color = "gray30",
#           size = 0.1) +
#   coord_sf(xlim = c(-118, 125), ylim = c(31, 36)) +
#   geom_point(data = clean_hab,
#              aes( x = longitude,
#                y = latitude),
#              fill = chlorophyll,
#              color = "gray10",
#              size = 3, 
#              alpha = 0.5) +
#   theme_minimal()+
#   coord_sf(datum = NA)


#now going to try to make it interactive
map_ca_hab <- tm_shape(sites_hab) +
  tm_bubbles(size = "chlorophyll", col = "green", border.col = "yellow")+
 tm_shape(coast_counties) +
  tm_fill("COUNTY", palette = "Set1", alpha = 0.5, legend.show = FALSE)+
  tm_view(basemaps = "Stamen.TerrainBackground")

tmap_mode("view")
#basemaps in leaflet::providers

tmap_leaflet(map_ca_hab)



```

going to try to gather and reshape the data into rows instead of columns

```{r}

gathered_hab <- sites_hab %>%
  gather(Variable,
         Data,
         akashiwo,
   alexandrium,
   ammonia,
  chlorophyll,
  domoic_acid,
    n_n,
    phosphate,
     pseudo_nitzschia_spp,
   silicate,
   water_temp)


```


